### ISSUE TITLE
Getting Master Key not Initilized error

### ISSUE THREAD

**Issue by VamsiKrishnaMyneni** [AKASHAorg/secure-webstore#11]
hi,
1. I am Getting Master Key not Initialized error when I released the code to Testing Environment
2. I am only using secure-store.js and including in the bundle (asp.net)
3. shall I include any other library file in my solution because in Localhost it works fine but not when I deployed to QA environment

![MicrosoftTeams-image](https://user-images.githubusercontent.com/32959424/107611114-429ec780-6c69-11eb-82be-5e989abdb363.png)

4. in the init().catch() block below error returned
![error cropped](https://user-images.githubusercontent.com/32959424/107636276-67f3fb80-6c92-11eb-8e9e-e77de90d33e6.png)

**Comment by deiu** [comment]
Hi,

You are probably trying to run this code on a non-secure connection (i.e. not HTTPS). The browser's native Webcrypto API (the one used by the library) blocks access to the crypto functions when not running over HTTPS. The only exception is for localhost.

**Comment by deiu** [comment]
I will close this issue assuming it resolved.
