### ISSUE TITLE
Not working with vue 2

### ISSUE THREAD

**Issue by Master-Y0da** [AKASHAorg/secure-webstore#14]
I try to set up with vue 2, like this:

`       

     import Vue from 'vue'
     import './plugins/axios'
     import App from './App.vue'

     const Store = require('secure-webstore')

     const store = new Store('user_data', 'lachiquichiqui89')

     store.init().then(() => {
       // store is ready
     })

    Vue.prototype.$store = store

    new Vue({
     router,
     render: h => h(App)
    }).$mount('#app')`

But gives me this error **Uncaught TypeError: Store is not a constructor**

**Comment by deiu** [comment]
Hi,

I've pushed a new build on npm with new modules. Try importing the Store like this: `const Store = require('secure-webstore').Store`. I will update the README to reflect this change.

**Comment by Master-Y0da** [comment]
working now! thanks @deiu
