### ISSUE TITLE
"Promise { <state>: "pending" }" after try to get data 

### ISSUE THREAD

**Issue by Master-Y0da** [AKASHAorg/secure-webstore#15]
I finally could create a DB and it's working fine: [caption](http://i.imgur.com/NBi5EGN.png) . But there is a problem when I try to get data in vue 2 project. 

First when I try:  **await store.get('info')** . I get error "can not use await outside async function".
So I try this:     

        let data = (async () => { await self.$store.get('info') })();
        console.log(data)`

And it seems to pass, except by the console that prints this:
`Promise { "pending" }
​
<state>: "fulfilled"
​
<value>: undefined`

So I can't get the data from my DB, I hope you can help me, thanks!!

**Comment by deiu** [comment]
I'm glad to hear you got it working!

On the other hand, the problem you have described above is not related to this library. I think you should look into how to [properly use await/async in Javascript](https://javascript.info/async-await). Alternatively you can also handle the promises in a classic way (using `then()`, etc.).

I am closing this issue as it is not related to the library.
