### ISSUE TITLE
The future of secure-webstore

### ISSUE THREAD

**Issue by deiu** [AKASHAorg/secure-webstore#19]
Hi @Jopie64 and @Arjen-1! I'm really glad to know you find this lib useful. Would you like to get in touch to discuss its future? For instance what you would like to see improved, any new features (e.g. support for other encryption algorithms, etc.).

You can contact me at andrei.sambra@akasha.world.

**Comment by deiu** [comment]
I will close this issue since there were no replies.

**Comment by Arjen-1** [comment]
@Jopie64 might get in touch with you. But he's on Holiday right now. Thanks again!

**Comment by Jopie64** [comment]
Hi @deiu,

Sorry for the late reply. As @Arjen-1 said I'm enjoying my holiday 😊 We work for the same company, hence he knows.
We use this library at our company for client side encryption of sensitive cache data. It does exactly as it's supposed to do, so we're happy with it! I'm not sure at the moment what more would be useful...
Sometimes it is kinda slow when requesting lots of data. I'm not sure whether it's the encryption or the db lib, but I assume it has to do with the browser implementation. So I didn't look into it as there's probably nothing we can do about it. I worked around it by keeping the cache in memory as well.

Thanks again for this great lib!

**Comment by deiu** [comment]
OK, I think I have a better idea now. Please let me know if there's anything I can help with in the future. 

And thanks for using the lib! 🙌
